- hosts: webservers
  become: yes
  vars_files:
    - vars/main.yml
  roles:
    - common
    - apache2

- hosts: proxy
  become: yes
  roles:
    - common
    - nginx

- hosts: database
  become: yes
  vars_files:
    - vars/main.yml
    - vars/vault.yml
  vars_prompt:
    - name: mysql_database
      prompt: Please enter the database name.
      private: no
  roles:
    - common
    - mysql

