# This playbook consists of two plays.
# The first play targets the hosts with the tag "webservers".
- hosts: webservers
  become: yes
  vars:
    http_port: 8000
    https_port: 4443
    html_welcome_msg: "Hello Scalefocus Academy!"
  roles:
    - common
    - apache2

# The second play targets the hosts with the tag "proxy".
- hosts: proxy
  become: yes
  roles:
    - common
    - nginx
